on:
  push:
    tags:
      - 'v*-voyager'

name: Create Release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Version
        run: echo ${{ github.ref }} > src/main/resources/insider-version
      - name: Build
        run: ./gradlew clean build --debug --stacktrace
      - name: Prepare Assets
        run: |
          mkdir insider
          mkdir insider/results
          cp README.md insider/README.md
          cp build/libs/insider*.jar insider/insider.jar
          cp bin/insider.sh insider/insider.sh
          chmod +x insider/insider.sh
          cp bin/insider.bat insider/insider.bat
          cp instrument.yml insider/instrument.yml
          cp languages.yml insider/languages.yml
          cp -R config insider/config
      - name: Create Archive
        run: zip -r insider.zip insider
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Insider ${{ github.ref }} (Voyager)
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./insider.zip
          asset_name: insider-voyager.zip
          asset_content_type: application/zip
